id = "cedar"
name = "Cedar"
version = "0.1.0"
schema_version = 1
authors = ["Cathal Mullan <contact@cathal.dev>"]
description = "Cedar language support for Zed"
repository = "https://github.com/DuskSystems/zed-cedar"

[grammars.cedar]
repository = "https://github.com/DuskSystems/tree-sitter-cedar"
path = "cedar"
commit = "f4be518f20f71ee62eaff4f3f1de07254c240704"

[grammars.cedarschema]
repository = "https://github.com/DuskSystems/tree-sitter-cedar"
path = "cedarschema"
commit = "f4be518f20f71ee62eaff4f3f1de07254c240704"

[language_servers.cedar-language-server]
name = "Cedar Language Server"
languages = ["Cedar", "Cedar Schema"]
