name = "Cedar Schema"
grammar = "cedarschema"
path_suffixes = ["cedarschema"]
line_comments = ["// "]
tab_size = 4
autoclose_before = ";:.,=}])>"
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false },
]
